### ISSUE TITLE
Search-ElasticV2 : ServerError: 400Type: search_phase_execution_exception Reason: "all shards failed"

### ISSUE THREAD

**Issue by banjoey** [gigi81/elastico#1]
Every time I try to run a basic query I get this error:
Search-ElasticV2 : ServerError: 400Type: search_phase_execution_exception Reason: "all shards failed"
I am using the query Kibana uses for a standard query with all the "fluff" stripped out, so I'm pretty sure the syntax is correct. I can run Get-ElasticV2Index on my cluster with no problems.

Can you provide me with a simple query (return 50 records or something) that I can try and troubleshoot my usage with?

**Comment by gigi81** [comment]
Hi @banjoey 
You can find the documentation for the query parameter here:
https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-query-string-query.html#query-string-syntax

Here some example searches:

Search-ElasticV2 -Index "logstash-*" -Query "EventID: 7036" -Size 50 -Verbose

Search-ElasticV2 -Node $nodes -Query "EventID: 7036" -Fields @("Hostname", "EventID", "Version") -Verbose

Let me know if it works out for you.

**Comment by banjoey** [comment]
I see what was happening now. I was trying to use the raw json query syntax instead of lucene syntax. Works like a charm now. Thanks you!

**Comment by gigi81** [comment]
No problem. Glad it works for you.
