### ISSUE TITLE
Limited to 10,000 results

### ISSUE THREAD

**Issue by SMAPPER** [gigi81/elastico#2]
Currently if I have a query with results larger than 10,000 I get the following error message:

"Result window is too large, from + size must be less than or equal to: [10000] but 
was [100000]. See the scroll api for a more efficient way to request large data sets. This limit can be set by changing the [index.max_result_window] index level setting."

Is there any way the scroll api can be added to allow retrieving more results?

**Comment by gigi81** [comment]
Hi @SMAPPER ,
I checked the elasticsearch API and what I can do is add a "-From" parameter to the cmdlet. In this way you will be able to do something like:
-From 0 -Size 10000
-From 10000 -Size 10000
-From 20000 -Size 10000
-From 30000 -Size 10000
... and so on, getting all the results until the cmdlet returns an empty resultset (or  aresultset with less than 10000 results)

**Comment by gigi81** [comment]
I published version 0.4 of the package that includes the -From parameter. Just run to upgrade it:
```powershell
Update-Module Elastico
````

**Comment by SMAPPER** [comment]
I just tested this and the -From parameter doesn't seem to be working properly. For example:

Search-ElasticV5 -Node es01.test.int:9200 -Index logstash-windows-* -from 10000 -Size 100

Throws an error of:

Search-ElasticV5 : ServerError: 500Type: search_phase_execution_exception Reason: "all shards failed" CausedBy: "Type: query_phase_execution_exception Reason: "Result window is too large, from + size must be less than or equal to: [10000] but was [10100]. See the scroll api for a more efficient way to request large data sets. This limit can be set by changing the [index.max_result_window] index level setting.""

Same search but with size of 10,000:
Search-ElasticV5 -Node es01.test.int:9200 -Index logstash-windows-* -from 10000 -Size 10000

Search-ElasticV5 : ServerError: 500Type: search_phase_execution_exception Reason: "all shards failed" CausedBy: "Type: query_phase_execution_exception Reason: "Result window is too large, from + size must be less than or equal to: [10000] but was [20000]. See the scroll api for a more efficient way to request large data sets. This limit can be set by changing the [index.max_result_window] index level setting.""

Do you know what would be causing this?
