### ISSUE TITLE
Security support

### ISSUE THREAD

**Issue by darynwilkinson** [gigi81/elastico#4]
Is there a way to specify credentials when using Search-ElasticV5?

**Comment by gigi81** [comment]
Sorry, not at the moment. PRs are welcome anyway

**Comment by gigi81** [comment]
Basic Authentication credentials can be specified on the node URI directly like:
http://username:password@localhost:9200

**Comment by gigi81** [comment]
Added support for basic authentication, client certificate and the possibility of ignoring ssl certificate issues (for example when using a self-signed certificate).
