### ISSUE TITLE
Unclear how to use....

### ISSUE THREAD

**Issue by svdoever** [gigi81/elastico#5]
Hi Gigi,

Thanks for the great powershell module, but I'm breaking my head over how to use it...

```
Install-Module Elastico

Get-ElasticV5ClusterHealth -Node "http://localhost:9200"
$result = Search-ElasticV5 -Node $Node -Index abbacampingsindex -Fields "websiteFields.campsiteId","websiteFields.images.image" -Size 100
$documents = $result.Documents
$documents.GetEnumerator() | ForEach-Object {
    $json = $_.websiteFields | ConvertTo-Json
    $json
}
```

does not work.... I see data, but can't get it out. I can convert to JSON string with ConvertTo-Json, but would like to access the fields.

Do you have some sample PowerShell code to show how to query and use results?

Regards,
Serge

**Comment by gigi81** [comment]
Hi @svdoever 
Not sure what you are trying to do here. And not sure what kind of objects you are storing in elasticsearch.
The -Fields parameter value doesn't look like to me. I would expect something like camspiteid,images
